### ISSUE TITLE
No Plugin Compatibility Information

### ISSUE THREAD

**Issue by justinlosh** [pitaj/nodebb-plugin-header-extend#1]
When you attempt to install the plugin through the ACP, you get the following error:

No Compatibility Infomation Found
This plugin did not specify a specific version for installation given your NodeBB version. Full compatibility cannot be guaranteed, and may cause your NodeBB to no longer start properly.

**Comment by pitaj** [comment]
This plugin is compatible with all recent versions of NodeBB (>0.5.0). Go
ahead and install it anyways, and I'll make the necessary changes when I
have time.

**Comment by pitaj** [comment]
Closed by 1fae13f2c0889ef70c15c76e7125212ba379e313
