### ISSUE TITLE
Hi. I just added the plugin, activated but when I add a new link, nothing happens. 

### ISSUE THREAD

**Issue by chinciusan** [pitaj/nodebb-plugin-header-extend#4]

**Comment by pitaj** [comment]
This plugin is still under development.

What version did you install? Did you install from npm or via git?

The npm version isn't updated to work with the newer versions of NodeBB

**Comment by chinciusan** [comment]
I installed it via ACP. 
nodebb-plugin-header-extend
This plugin adds the ability to create custom header icons and menus

Latest 0.1.3

I have NodeBB  0.7

**Comment by pitaj** [comment]
That ability is already in NodeBB core, I think. This plugin isn't
compatible with 0.7.x versions of NodeBB.

**Comment by chinciusan** [comment]
ok. I've seen some discussions about it, but it doesn't work for me even if I add http or https in the menu route. Thanks.
