### ISSUE TITLE
Plugin conflicts with Persona theme menu

### ISSUE THREAD

**Issue by Errapolis** [pitaj/nodebb-plugin-header-extend#5]
Deactivated this plugin - it seems to be conflicting with Persona theme's menu. When activated, users on mobile browsers (tested Safari iOS, Chrome iOS & Chrome Android) click menu (hamburger icon) and it doesn't respond.

Using NodeBB 8.1, Persona Theme

**Comment by pitaj** [comment]
Uh yeah, this plugin is not compatible with anything over 0.6.X

I'm planning on upgrading it soon, though.

**Comment by Errapolis** [comment]
Thanks @pitaj - 0.8.1's plugin menu in ACP filters only plugins which are compatible, it must have slipped through the net. Thank you.
