### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by michalliu** [pitaj/nodebb-plugin-header-extend#7]
My nodebb is cloned from https://github.com/NodeBB/NodeBB master branch today. The menu is not shown. My site is http://cn.mqmaker.com

**Comment by pitaj** [comment]
This plugin doesn't work with newer versions of NodeBB.

**Comment by michalliu** [comment]
May i know which nodebb version it supports?

**Comment by pitaj** [comment]
Something like 0.7, but most of the functionality in this plugin was
introduced into core and is present in 1.0, so you don't really need this
plugin.

**Comment by michalliu** [comment]
Noted, Thanks very much.
